<?php

namespace SBS\AdminstrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagePrdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagePrdRepository extends EntityRepository
{
}
